name: GitHub-Profile-Summary-Cards

on:
  schedule: # execute every 24 hours
    - cron: '* */24 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate

    steps:
      - uses: actions/checkout@v2
      - uses: hans-arn/github-profile-summary-cards@release
        env: # default use ${{ secrets.GITHUB_TOKEN }}, you can change to your personal access token
          GITHUB_TOKEN: ${{ secrets.HANS_PAT }}
        with:
          USERNAME: ${{ github.repository_owner }}
